### ISSUE TITLE
Using variables in the loop

### ISSUE THREAD

**Issue by netsi1964** [outpunk/postcss-each#19]
I would like to use two variables to iterate over like:
```
  --Font-sizes: xs, s, m, l, xl, xxl;
  --Font-sizes-values: 10px, 12px, 14px, 18px, 24px, 36px;
```
using 
```
@each $fontSize, $fontSizeValue in (var(--Font-sizes)), (var(--Font-sizes-values)) {
  .header-$(fontSize) {
    font-size: $(fontSizeValue)px;
  }
}

```
Is that supported?

It seems that the variables are not passed, even if I have `postcss-custom-properties` processor in my Gulp flow.

**Comment by outpunk** [comment]
Please, show me your PostCSS config.

**Comment by Grawl** [comment]
I am trying to switch from Sass to PostCSS, so I found a working solution to use variables in `@each` statement with this plugin and [`postcss-at-rules-variables`](https://github.com/GitScrum/postcss-at-rules-variables).

`postcss.json`

```json
{
  "input": "style.sss",
  "output": "style.css",
  "parser": "sugarss",
  "use": [
    "postcss-at-rules-variables",
    "postcss-custom-properties",
    "postcss-each"
  ],
  "local-plugins": true
}
```

`style.sss` (SugarSS)

```sugarss
:root
	--colors-names: (good, bad, purple)
	--color-values: (hsl(95, 63%, 46%), hsl(6, 63%, 46%), purple)
.item
	@each $name, $color in var(--colors-names), var(--color-values)
		&-$name
			color: $color
```

The code above is equals to this Sass:

```sass
$colors: (good: hsl(95, 63%, 46%), bad: hsl(6, 63%, 46%), purple: purple)
.item
  @each $name, $color in $colors
    &-#{$name}
      color: $color
```

Notice that I cannot use “map” like in Sass: `(name: color, name: color)`. I have to combine two lists instead, and there is no option to make it in a different way.

Notice that I cannot use `postcss-simple-vars` because of [strange error](https://github.com/outpunk/postcss-each/issues/14#issuecomment-261951230) between this two plugins. Sad, I like more to define variables in Sass way, not W3C `:root` style.

**Comment by lan3jur** [comment]
@Grawl Thank you for this solution!
I have a question though: How do I pass a variable in a second @each loop?
Example:
```
:root {
	--grid-breakpoints-names       : (xs, sm, md, lg, xl);
	--grid-breakpoints-values      : (0, 576px, 768px, 992px, 1200px);
	--responsive-headings-names    : (h1-responsive, h2-responsive, h3-responsive, h4-responsive, h5-responsive);
	--responsive-headings-values-xs: (150%, 145%, 135%, 135%, 135%);
	--responsive-headings-values-sm: (170%, 140%, 125%, 125%, 125%);
}

@each $value, $name in var(--grid-breakpoints-values), var(--grid-breakpoints-names) {
	@media (min-width: $value) {
		@each $heading, $size in var(--responsive-headings-names), var(--responsive-headings-values-$name) {
			.$heading {
				font-size: $size;
			}
		}
	}
}
```

Thanks!
