### ISSUE TITLE
Option to split with spaces or comma

### ISSUE THREAD

**Issue by corysimmons** [outpunk/postcss-each#24]
Defaults to comma now, but it'd be nice if there was an option to split with spaces as well: `@each $size in (10px 20px) by space { ... }`

Could even accept a string to split by: `@each $size in (10px 20px) by ' ' { ... }`

Gonna go ahead and fork because I need this functionality pretty bad, but let me know if you're interested in a PR.

**Comment by outpunk** [comment]
You have a good idea. But it's not good option to include this into `postcss-each`, because this approach doesn't follow the modular [PostCSS philosophy](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#12-do-one-thing-and-do-it-well). 

It would be much better to write `postcss-list` or `postcss-array` plugin to translate different list types into another ones and use it along with `postcss-each` and other plugins.

**Comment by ai** [comment]
I agree, adding `by sep` will make plugin more complicated

**Comment by corysimmons** [comment]
:+1:
